#if TOOLS
using System;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;

namespace Godot.Achievements.Core.Editor;

/// <summary>
/// Generates a C# file containing constants for all achievement IDs.
/// This enables type-safe access to achievements instead of using magic strings.
/// </summary>
public static partial class AchievementConstantsGenerator
{
    /// <summary>
    /// Result of a code generation operation
    /// </summary>
    public class GenerationResult
    {
        public bool Success { get; init; }
        public string? ErrorMessage { get; init; }
        public int GeneratedCount { get; init; }
        public string? OutputPath { get; init; }
    }

    /// <summary>
    /// Generates a C# file with constants for all achievement IDs in the database.
    /// </summary>
    /// <param name="database">The achievement database to generate constants from</param>
    /// <param name="outputPath">The file path to write the generated code to</param>
    /// <param name="className">The name of the generated class (default: "AchievementIds")</param>
    /// <param name="namespaceName">Optional namespace for the generated class</param>
    /// <returns>A result indicating success or failure</returns>
    public static GenerationResult Generate(
        AchievementDatabase database,
        string outputPath,
        string className = "AchievementIds",
        string? namespaceName = null)
    {
        if (database == null)
        {
            return new GenerationResult
            {
                Success = false,
                ErrorMessage = "Database is null"
            };
        }

        if (string.IsNullOrWhiteSpace(outputPath))
        {
            return new GenerationResult
            {
                Success = false,
                ErrorMessage = "Output path is empty"
            };
        }

        if (database.Achievements.Count == 0)
        {
            return new GenerationResult
            {
                Success = false,
                ErrorMessage = "Database contains no achievements"
            };
        }

        try
        {
            var code = GenerateCode(database, className, namespaceName);

            // Resolve Godot path to filesystem path if needed
            var resolvedPath = ResolvePath(outputPath);

            // Ensure directory exists
            var directory = Path.GetDirectoryName(resolvedPath);
            if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }

            File.WriteAllText(resolvedPath, code, Encoding.UTF8);

            return new GenerationResult
            {
                Success = true,
                GeneratedCount = database.Achievements.Count,
                OutputPath = resolvedPath
            };
        }
        catch (Exception ex)
        {
            return new GenerationResult
            {
                Success = false,
                ErrorMessage = $"Failed to generate constants: {ex.Message}"
            };
        }
    }

    /// <summary>
    /// Generates the C# source code for the constants class.
    /// </summary>
    private static string GenerateCode(
        AchievementDatabase database,
        string className,
        string? namespaceName)
    {
        var sb = new StringBuilder();

        // Header comment
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// This file was generated by the Achievement Constants Generator.");
        sb.AppendLine("// Do not modify this file directly - changes will be overwritten.");
        sb.AppendLine($"// Generated at: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();

        // Namespace (if provided)
        var hasNamespace = !string.IsNullOrWhiteSpace(namespaceName);
        if (hasNamespace)
        {
            sb.AppendLine($"namespace {namespaceName};");
            sb.AppendLine();
        }

        // Class declaration
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Contains constants for all achievement IDs defined in the database.");
        sb.AppendLine("/// Use these constants instead of hardcoding achievement ID strings.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");

        // Track used identifiers to handle duplicates
        var usedIdentifiers = new System.Collections.Generic.HashSet<string>(StringComparer.Ordinal);

        // Generate constants for each achievement
        foreach (var achievement in database.Achievements)
        {
            if (string.IsNullOrWhiteSpace(achievement.Id))
            {
                continue; // Skip achievements without IDs
            }

            var identifier = ConvertToIdentifier(achievement.Id);

            // Handle duplicate identifiers by appending a suffix
            var originalIdentifier = identifier;
            var suffix = 2;
            while (usedIdentifiers.Contains(identifier))
            {
                identifier = $"{originalIdentifier}_{suffix}";
                suffix++;
            }
            usedIdentifiers.Add(identifier);

            // Add XML documentation if display name is available
            if (!string.IsNullOrWhiteSpace(achievement.DisplayName))
            {
                sb.AppendLine($"    /// <summary>");
                sb.AppendLine($"    /// {EscapeXmlComment(achievement.DisplayName)}");
                if (!string.IsNullOrWhiteSpace(achievement.Description))
                {
                    sb.AppendLine($"    /// <para>{EscapeXmlComment(achievement.Description)}</para>");
                }
                sb.AppendLine($"    /// </summary>");
            }

            sb.AppendLine($"    public const string {identifier} = \"{EscapeString(achievement.Id)}\";");
            sb.AppendLine();
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Converts an achievement ID to a valid C# identifier.
    /// Examples:
    ///   "achievement_01" -> "Achievement01"
    ///   "first-blood" -> "FirstBlood"
    ///   "kill_100_enemies" -> "Kill100Enemies"
    ///   "123_start" -> "_123Start"
    /// </summary>
    public static string ConvertToIdentifier(string id)
    {
        if (string.IsNullOrWhiteSpace(id))
        {
            return "_Empty";
        }

        var sb = new StringBuilder();
        var capitalizeNext = true;

        foreach (var c in id)
        {
            if (char.IsLetterOrDigit(c))
            {
                if (capitalizeNext && char.IsLetter(c))
                {
                    sb.Append(char.ToUpper(c, CultureInfo.InvariantCulture));
                    capitalizeNext = false;
                }
                else
                {
                    sb.Append(c);
                    capitalizeNext = false;
                }
            }
            else
            {
                // Non-alphanumeric characters trigger capitalization of the next letter
                capitalizeNext = true;
            }
        }

        var result = sb.ToString();

        // C# identifiers cannot start with a digit
        if (result.Length > 0 && char.IsDigit(result[0]))
        {
            result = "_" + result;
        }

        // Handle empty result
        if (string.IsNullOrEmpty(result))
        {
            result = "_Invalid";
        }

        // Ensure it's not a C# keyword
        result = EnsureNotKeyword(result);

        return result;
    }

    /// <summary>
    /// Ensures the identifier is not a C# reserved keyword.
    /// </summary>
    private static string EnsureNotKeyword(string identifier)
    {
        // List of C# keywords that could conflict with identifiers
        var keywords = new[]
        {
            "abstract", "as", "base", "bool", "break", "byte", "case", "catch",
            "char", "checked", "class", "const", "continue", "decimal", "default",
            "delegate", "do", "double", "else", "enum", "event", "explicit", "extern",
            "false", "finally", "fixed", "float", "for", "foreach", "goto", "if",
            "implicit", "in", "int", "interface", "internal", "is", "lock", "long",
            "namespace", "new", "null", "object", "operator", "out", "override",
            "params", "private", "protected", "public", "readonly", "ref", "return",
            "sbyte", "sealed", "short", "sizeof", "stackalloc", "static", "string",
            "struct", "switch", "this", "throw", "true", "try", "typeof", "uint",
            "ulong", "unchecked", "unsafe", "ushort", "using", "virtual", "void",
            "volatile", "while"
        };

        if (keywords.Contains(identifier.ToLowerInvariant()))
        {
            return "@" + identifier;
        }

        return identifier;
    }

    /// <summary>
    /// Escapes a string for use in C# code.
    /// </summary>
    private static string EscapeString(string value)
    {
        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r")
            .Replace("\t", "\\t");
    }

    /// <summary>
    /// Escapes a string for use in XML documentation comments.
    /// </summary>
    private static string EscapeXmlComment(string value)
    {
        return value
            .Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;");
    }

    /// <summary>
    /// Resolves a Godot resource path (res://) to a filesystem path.
    /// </summary>
    private static string ResolvePath(string path)
    {
        if (path.StartsWith("res://"))
        {
            return ProjectSettings.GlobalizePath(path);
        }
        return path;
    }
}
#endif
