// <auto-generated>
// This file was generated by the Achievement Constants Generator.
// Do not modify this file directly - changes will be overwritten.
// Generated at: 2026-01-03 17:22:36 UTC
// </auto-generated>

/// <summary>
/// Contains constants for all achievement IDs defined in the database.
/// Use these constants instead of hardcoding achievement ID strings.
/// </summary>
public static class AchievementIds
{
    /// <summary>
    /// Hit the button!
    /// <para>Just click any button!</para>
    /// </summary>
    public const string Achievement01 = "achievement_01";

    /// <summary>
    /// Hit the button 20x!
    /// <para>Hit the button 20 times!</para>
    /// </summary>
    public const string Achievement05 = "achievement_05";

}
